version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db:/data/db

volumes:
  db:
