services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - net

  mongodb:
    container_name: mongodb
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db:/data/db
    networks:
      - net

volumes:
  db:

networks:
  net:
    driver: bridge